"""
Extract named Items (1A Risk Factors, 7 MD&A, ...) from a 10-K/10-Q.

This is the step everyone underestimates. Filings are HTML generated by a
dozen different vendors, so there is no schema to rely on. What DOES hold
across essentially all filers:

  - Items appear in order, as headings, in the body text.
  - The table of contents ALSO contains every heading, near the top.

So the naive `find("Item 1A")` grabs the TOC entry and yields ~40 characters
of nothing. The fix below is to find every candidate boundary and pick the
pair that encloses the most text. Document this reasoning in your README --
"I noticed the TOC collision and solved it by span length" is exactly the
kind of thing an interviewer digs into.
"""

import re
from bs4 import BeautifulSoup

# Where each section ends. 10-Q uses a different numbering scheme than 10-K,
# so we key on the start item and list plausible terminators.
BOUNDARIES = {
    "1A": ["item 1b", "item 2"],
    "7": ["item 7a", "item 8"],
    "7A": ["item 8"],
    "2": ["item 3"],  # 10-Q MD&A lives in Part I Item 2
}


def html_to_text(html: str) -> str:
    """
    Flatten filing HTML to plain text.

    Tables are dropped: they are almost entirely financial statements, they
    destroy the text flow, and the numbers are better pulled from XBRL later.
    Non-breaking spaces are normalised because filers use them constantly and
    they break naive regex matching.
    """
    soup = BeautifulSoup(html, "html.parser")

    for tag in soup(["script", "style", "table"]):
        tag.decompose()

    # Insert an explicit break after every block-level element BEFORE
    # flattening. Without this, filers whose paragraphs are <div>/<span>
    # (Apple, among many) collapse into a handful of enormous blobs, because
    # get_text only emits a single newline between nodes and there is then no
    # blank line left to split on downstream.
    for tag in soup.find_all(["p", "div", "br", "li", "h1", "h2", "h3", "h4"]):
        tag.insert_after(soup.new_string("\n\n"))

    text = soup.get_text(separator="\n")
    text = text.replace("\xa0", " ")
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n\s*\n+", "\n\n", text)
    return text.strip()


# Words that, following "Item 1A", mean this is a sentence referring to the
# section rather than the section heading itself. Apple's forward-looking
# statements preamble ("...described in Item 1A of this Form 10-K under the
# heading Risk Factors...") sits before the real section, so without this it
# produces the longest span and wins.
_CROSSREF = re.compile(
    r"^\s*(of|in|to|under|and|or|above|below|entitled|hereof|herein|through)\b",
    re.IGNORECASE,
)


def _find_all(text: str, item: str) -> list[int]:
    """
    Every offset where an item heading plausibly starts.

    Two filters, both learned from real filings:

      1. The heading must begin a line. Inline mentions mid-sentence are
         cross-references, not headings.
      2. What follows must not read as a cross-reference clause.

    Filers write "Item 1A.", "ITEM 1A -", "Item 1A:" and so on, so the
    trailing separator stays optional.
    """
    pattern = rf"^\s*item\s*{re.escape(item)}\s*[\.\-–—:]?"
    out = []
    for m in re.finditer(pattern, text, re.IGNORECASE | re.MULTILINE):
        if _CROSSREF.match(text[m.end() : m.end() + 30]):
            continue
        out.append(m.start())
    return out


def extract_item(text: str, item: str) -> str | None:
    """
    Pull one Item's body text.

    Strategy: consider every (start, end) pair of candidate headings and keep
    the longest resulting span. The TOC entries sit adjacent to each other and
    produce tiny spans; the real body produces a large one.
    """
    starts = _find_all(text, item)
    if not starts:
        return None

    ends = []
    for terminator in BOUNDARIES.get(item.upper(), []):
        ends.extend(_find_all(text, terminator.replace("item ", "")))

    best = None
    for s in starts:
        candidates = [e for e in ends if e > s]
        stop = min(candidates) if candidates else len(text)
        span = text[s:stop]
        if best is None or len(span) > len(best):
            best = span

    # Anything under ~1000 chars is a TOC artifact, not a real section.
    if best is None or len(best) < 1000:
        return None
    return best.strip()


def extract_sections(html: str, items=("1A", "7")) -> dict[str, str]:
    """Convenience wrapper: HTML in, {item: body_text} out."""
    text = html_to_text(html)
    return {
        item: body
        for item in items
        if (body := extract_item(text, item)) is not None
    }
